// flow-typed signature: 5607a479c24c6bc8da5bb2834e373c50
// flow-typed version: <<STUB>>/highland_v^2.10.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'highland'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'highland' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'highland/dist/highland' {
  declare module.exports: any;
}

declare module 'highland/dist/highland.min' {
  declare module.exports: any;
}

declare module 'highland/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'highland/dist/highland.js' {
  declare module.exports: $Exports<'highland/dist/highland'>;
}
declare module 'highland/dist/highland.min.js' {
  declare module.exports: $Exports<'highland/dist/highland.min'>;
}
declare module 'highland/lib/index.js' {
  declare module.exports: $Exports<'highland/lib/index'>;
}
