// flow-typed signature: 40a41440e52e2f9c67689ad2761e0b8e
// flow-typed version: <<STUB>>/mongo_v^0.1.0/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'mongo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'mongo' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'mongo/index' {
  declare module.exports: $Exports<'mongo'>;
}
declare module 'mongo/index.js' {
  declare module.exports: $Exports<'mongo'>;
}
