// flow-typed signature: 3d315339b082ab19d318daf1da39f0c1
// flow-typed version: <<STUB>>/rabbit.js_v^0.4.4/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rabbit.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rabbit.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rabbit.js/example/easyamqp/server' {
  declare module.exports: any;
}

declare module 'rabbit.js/example/net/server' {
  declare module.exports: any;
}

declare module 'rabbit.js/example/ordering/server' {
  declare module.exports: any;
}

declare module 'rabbit.js/example/socketio/server' {
  declare module.exports: any;
}

declare module 'rabbit.js/example/sockjs/server' {
  declare module.exports: any;
}

declare module 'rabbit.js/lib/sockets' {
  declare module.exports: any;
}

declare module 'rabbit.js/test/tests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rabbit.js/example/easyamqp/server.js' {
  declare module.exports: $Exports<'rabbit.js/example/easyamqp/server'>;
}
declare module 'rabbit.js/example/net/server.js' {
  declare module.exports: $Exports<'rabbit.js/example/net/server'>;
}
declare module 'rabbit.js/example/ordering/server.js' {
  declare module.exports: $Exports<'rabbit.js/example/ordering/server'>;
}
declare module 'rabbit.js/example/socketio/server.js' {
  declare module.exports: $Exports<'rabbit.js/example/socketio/server'>;
}
declare module 'rabbit.js/example/sockjs/server.js' {
  declare module.exports: $Exports<'rabbit.js/example/sockjs/server'>;
}
declare module 'rabbit.js/index' {
  declare module.exports: $Exports<'rabbit.js'>;
}
declare module 'rabbit.js/index.js' {
  declare module.exports: $Exports<'rabbit.js'>;
}
declare module 'rabbit.js/lib/sockets.js' {
  declare module.exports: $Exports<'rabbit.js/lib/sockets'>;
}
declare module 'rabbit.js/test/tests.js' {
  declare module.exports: $Exports<'rabbit.js/test/tests'>;
}
