// flow-typed signature: 2db7a1e735d4b65b65e1992230144420
// flow-typed version: <<STUB>>/rsmq_v^0.7.1/flow_v0.33.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'rsmq'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'rsmq' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'rsmq/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'rsmq/index' {
  declare module.exports: $Exports<'rsmq'>;
}
declare module 'rsmq/index.js' {
  declare module.exports: $Exports<'rsmq'>;
}
declare module 'rsmq/test/test.js' {
  declare module.exports: $Exports<'rsmq/test/test'>;
}
